#!/bin/bash

#colors
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

#parse_yaml function
parse_yaml() {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}


# Check YAML files
if [ ! -f .t3.sync.yaml ]; then
    echo ".t3.sync.yaml not found!"
    cp ~/bin_t3/lib/.t3.sync.yaml .t3.sync.yaml
    (echo "" && echo ".t3.sync.yaml") >> .gitignore
    exit
fi

# Read yaml file
load_yaml() {
    eval $(parse_yaml .t3.sync.yaml "secret_")
}

#General variables
NOVAR="Missing entry in the YAML"

load_yaml

UTF8='--default-character-set=utf8'

echo
echo "Develop >>"
echo "Webspace User:" $secret_develop_user
echo "Webspace User:" $secret_develop_host
echo "Webspace Path:" $secret_develop_path
echo "MySQL Database:" $secret_develop_mysql_database
echo "MySQL User:" $secret_develop_mysql_user
echo "MySQL Host:" $secret_develop_mysql_host
echo "MySQL Password:" $secret_develop_mysql_pw
echo

echo "Master >>"
echo "Webspace User:" $secret_master_user
echo "Webspace User:" $secret_master_host
echo "Webspace Path:" $secret_master_path
echo "MySQL Database:" $secret_master_mysql_database
echo "MySQL User:" $secret_master_mysql_user
echo "MySQL Host:" $secret_master_mysql_host
echo "MySQL Password:" $secret_master_mysql_pw
echo

echo "Local >>"
echo "Domain:" $secret_local_domain
echo "Webroot:" $secret_local_webroot
echo "MySQL Database:" $secret_local_mysql_database
echo "MySQL User:" $secret_local_mysql_user
echo "MySQL Host:" $secret_local_mysql_host
echo "MySQL Password:" $secret_local_mysql_pw
echo

if [ -z "$secret_local_mysql_database" ]
then
	printf $RED
	echo "Please update your .t3.sync.yaml file - Have a look here:"
	echo "https://github.com/Startpiloten/bin_t3/blob/master/lib/.t3.sync.yaml"
	printf $NC
	exit
fi

printf $NC

sync_develop_db_files(){
	ssh ${secret_develop_user}@${secret_develop_host} mysqldump ${UTF8} -u${secret_develop_mysql_user} -p${secret_develop_mysql_pw} -h${secret_develop_mysql_host} ${secret_develop_mysql_database} | mysql ${UTF8} -p${secret_local_mysql_pw} -u${secret_local_mysql_user} -h${secret_local_mysql_host} ${secret_local_mysql_database}

	rsync -avz --exclude '_processed_' $secret_develop_user@$secret_develop_host:$secret_develop_path/fileadmin ${secret_local_webroot}/
	rsync -avz --exclude '_processed_' $secret_develop_user@$secret_develop_host:$secret_develop_path/uploads ${secret_local_webroot}/

}

sync_develop_db(){
	ssh ${secret_develop_user}@${secret_develop_host} mysqldump ${UTF8} -u${secret_develop_mysql_user} -p${secret_develop_mysql_pw} -h${secret_develop_mysql_host} ${secret_develop_mysql_database} | mysql ${UTF8} -p${secret_local_mysql_pw} -u${secret_local_mysql_user} -h${secret_local_mysql_host} ${secret_local_mysql_database}

}

sync_develop_dbfile(){
	ssh ${secret_develop_user}@${secret_develop_host} mysqldump ${UTF8} -u${secret_develop_mysql_user} -p${secret_develop_mysql_pw} -h${secret_develop_mysql_host} ${secret_develop_mysql_database} > ${secret_develop_mysql_database}.sql

}


sync_master_db_files(){
	ssh ${secret_master_user}@${secret_master_host} mysqldump ${UTF8} -u${secret_master_mysql_user} -p${secret_master_mysql_pw} -h${secret_master_mysql_host} ${secret_master_mysql_database} | mysql ${UTF8} -p${secret_local_mysql_pw} -u${secret_local_mysql_user} -h${secret_local_mysql_host} ${secret_local_mysql_database}

	rsync -avz --exclude '_processed_' $secret_master_user@$secret_master_host:$secret_master_path/fileadmin ${secret_local_webroot}/
	rsync -avz --exclude '_processed_' $secret_master_user@$secret_master_host:$secret_master_path/uploads ${secret_local_webroot}/
}

sync_master_db(){
	ssh ${secret_master_user}@${secret_master_host} mysqldump ${UTF8} -u${secret_master_mysql_user} -p${secret_master_mysql_pw} -h${secret_master_mysql_host} ${secret_master_mysql_database} | mysql ${UTF8} -p${secret_local_mysql_pw} -u${secret_local_mysql_user} -h${secret_local_mysql_host} ${secret_local_mysql_database}
}

sync_master_dbfile(){
	ssh ${secret_master_user}@${secret_master_host} mysqldump ${UTF8} -u${secret_master_mysql_user} -p${secret_master_mysql_pw} -h${secret_master_mysql_host} ${secret_master_mysql_database} > ${secret_master_mysql_database}.sql
}

printf ${ORANGE}
echo "======================="
echo "T3 Sync - Please Select"
echo "======================="
printf ${NC}

COLUMNS=10
PS3='Please enter your choice: '
options=(
    "Sync Develop (DB and Files)"
    "Sync Develop (DB only)"
    "Get  Develop (DB as File)"
    "Sync Master (DB and Files)"
    "Sync Master (DB only)"
    "Get  Master (DB as File)"
    "Quit"
)
select opt in "${options[@]}"
do
    case $opt in
        "Sync Develop (DB and Files)")
            sync_develop_db_files
            exit
            ;;
        "Sync Develop (DB only)")
            sync_develop_db
            exit
            ;;
        "Get  Develop (DB as File)")
            sync_develop_dbfile
            exit
            ;;
        "Sync Master (DB and Files)")
            sync_master_db_files
            exit
            ;;
        "Sync Master (DB only)")
            sync_master_db
            exit
            ;;
        "Get  Master (DB as File)")
            sync_master_dbfile
            exit
            ;;
        "Quit")
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done
